name: Update Translations

on:
  workflow_dispatch:

jobs:
  update-i18n:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Update submodule and commit changes
        run: |
          git submodule update --remote --merge
          git add public/locales
          git commit -m "Update translations" || echo "No changes to commit"
          git push
