name: Update Translations

on:
  workflow_dispatch:

permissions:
  contents: write # Crucial for pushing changes back to the main repo

jobs:
  update-i18n:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive # Keep this as recursive for initial checkout
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      # --- NEW STEP: Pull latest changes into the submodule from its remote ---
      - name: Pull latest translations into submodule
        run: |
          echo "Updating submodule 'public/locales' to its latest remote state..."
          # This command explicitly fetches and merges the latest changes
          # from the submodule's remote tracking branch.
          git submodule update --remote --merge public/locales
          echo "Submodule update attempted."

      - name: Stage and Commit Submodule Changes to Main Repo
        run: |
          # Check if the submodule's tracked commit hash has changed in the parent repo
          if git diff --exit-code public/locales; then
            echo "No changes detected in the submodule commit hash. Skipping commit."
          else
            echo "Changes detected in the submodule commit hash. Staging and committing..."
            git add public/locales # Stage the change in the submodule's commit hash
            git commit -m "🔁 Update translations from Weblate"
            git push # This push should now succeed
          fi
