name: Update Translations

on:
  workflow_dispatch:

jobs:
  update-i18n:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo with submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Synchronize and Initialize Submodule Configuration
        run: |
          echo "Attempting to synchronize submodule configuration..."
          git submodule sync

          echo "Initializing and updating submodule recursively..."
          git submodule update --init --recursive

          echo "Verifying the submodule URL after sync and update..."
          git config --get submodule.public/locales.url || echo "Submodule URL not found in Git config, might be a path issue."

      - name: Update submodule content and commit changes to main repo
        run: |
          echo "Pulling latest changes from the submodule's remote (allowing unrelated histories if necessary)..."
          # *** IMPORTANT CHANGE HERE ***
          # Add --allow-unrelated-histories to the merge operation within the submodule update
          git submodule update --remote --merge --allow-unrelated-histories

          # Check if there are any changes in the submodule's commit hash
          if git diff --exit-code public/locales; then
            echo "No changes detected in the submodule commit hash. Skipping commit."
          else
            echo "Changes detected in the submodule commit hash. Staging and committing..."
            git add public/locales
            git commit -m "Update translations from Weblate"
            git push
          fi
