name: Push new source strings to translation repo

on:
  push:
    # This action will now trigger on ANY push to the 'main' branch
    # (no longer limited by specific paths like 'public/locales/en/translation.json')
    branches:
      - main
  workflow_dispatch: # Keep this to allow manual triggering

permissions:
  contents: read

jobs:
  push-source-translations:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo with submodules
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.WEBLATE_PUSH_TOKEN }}
          submodules: recursive

      - name: Configure Git identity
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Get Submodule Path and Source File
        id: get_paths
        run: |
          SUBMODULE_PATH=$(git config --file .gitmodules --get-regexp '^submodule\..*\.path$' | awk '{print $2}')
          SOURCE_FILE_PATH="en/translation.json" # Still assumes this is your source file relative to submodule

          if [ -z "$SUBMODULE_PATH" ]; then
            echo "Error: Could not find submodule path in .gitmodules."
            exit 1
          fi

          echo "Dynamically determined submodule path: ${SUBMODULE_PATH}"
          echo "Source translation file path (relative to submodule): ${SOURCE_FILE_PATH}"

          echo "submodule_path=${SUBMODULE_PATH}" >> "$GITHUB_OUTPUT"
          echo "source_file_path=${SOURCE_FILE_PATH}" >> "$GITHUB_OUTPUT"

      - name: Commit and push changes in submodule
        run: |
          cd ${{ steps.get_paths.outputs.submodule_path }}

          git checkout main || git checkout -b main

          # This check is still important to only commit if the file genuinely changed.
          # Otherwise, it would create empty commits in the submodule for unrelated main branch pushes.
          if git diff --quiet ${{ steps.get_paths.outputs.source_file_path }}; then
            echo "No changes detected in ${{ steps.get_paths.outputs.source_file_path }} within the submodule. Skipping commit."
          else
            echo "Changes detected in ${{ steps.get_paths.outputs.source_file_path }}. Staging and committing..."
            git add ${{ steps.get_paths.outputs.source_file_path }}
            git commit -m "feat: Update source strings for Weblate"
            git push https://gediminasurvila:${{ secrets.WEBLATE_PUSH_TOKEN }}@github.com/gediminasurvila/react-weblate-i18n.git main
            echo "Source strings pushed to translation repository."
          fi
