name: Push en.json to Translation Repo

on:
  push:
    paths:
      - "public/translations/locales/en.json"
    branches:
      - main

  workflow_dispatch: # Allow manual trigger as well

permissions:
  contents: read

jobs:
  push-en-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main repo
        uses: actions/checkout@v4

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Clone translations repo
        run: |
          git clone https://gediminasurvila:${{ secrets.WEBLATE_PUSH_TOKEN }}@github.com/gediminasurvila/react-weblate-i18n.git translations-repo
          ls translations-repo

      - name: Copy updated en.json
        run: |
          cp public/translations/locales/en.json translations-repo/locales/en.json

      - name: Commit & push to translations repo
        working-directory: translations-repo
        run: |
          git add locales/en.json

          if git diff --cached --quiet; then
            echo "No changes to commit. Skipping push."
          else
            git commit -m "chore: update source language file en.json"
            git push origin main
          fi
